-- XTREAM SERVER 8.1 FINAL MIGRATION
-- Execute após backup do banco.
CREATE TABLE IF NOT EXISTS admin_logs (
 id INT AUTO_INCREMENT PRIMARY KEY,
 action VARCHAR(255),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
